[package]
name = "dalang-protocol"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmp = "^0.8.2"
rmpv = "^1.0.0"

protocol-derive = { path = "../protocol-derive" }